# Generated by Django 3.0.5 on 2020-05-02 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(db_index=True, default=0, help_text='The status of this instance'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 13, 26, 8, 823720), help_text='Updated when ths status of this instance changes'),
            preserve_default=False,
        ),
    ]
