# Generated by Django 3.0.5 on 2020-05-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200502_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Enabled'), (1, 'Deleted'), (2, 'Suspended'), (3, 'Archived')], db_index=True, default=0, help_text='The status of this instance'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_update_timestamp',
            field=models.DateTimeField(editable=False, help_text='Updated when ths status of this instance changes'),
        ),
    ]
