# Generated by Django 3.0.5 on 2020-05-03 10:25

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('stitchers', '0001_initial'),
        ('projects', '0003_auto_20200502_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Enabled'), (1, 'Deleted'), (2, 'Suspended'), (3, 'Archived')], db_index=True, default=0, help_text='The status of this instance')),
                ('status_update_timestamp', models.DateTimeField(editable=False, help_text='Updated when ths status of this instance changes')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.IntegerField(default=0, editable=False, help_text='The size of the file in bytes')),
                ('owner', models.ForeignKey(blank=True, help_text='Null allowed for things like files used in the system or a base suite of templates', null=True, on_delete=django.db.models.deletion.CASCADE, to='stitchers.Stitcher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('mediaitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.MediaItem')),
                ('file', models.FileField(upload_to=projects.models.MediaItem.upload_to, validators=[projects.models.FileValidatorFunction(allowed_extensions=[], allowed_mimetypes=['audio/vnd.wave', 'audio/wav', 'audio/wave', 'audio/x-wav'], max_file_size=None)])),
            ],
            options={
                'abstract': False,
            },
            bases=('projects.mediaitem',),
        ),
        migrations.CreateModel(
            name='DocumentAsset',
            fields=[
                ('mediaitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.MediaItem')),
                ('file', models.FileField(upload_to=projects.models.MediaItem.upload_to, validators=[projects.models.FileValidatorFunction(allowed_extensions=[], allowed_mimetypes=['text/text', 'application/pdf'], max_file_size=None)])),
            ],
            options={
                'abstract': False,
            },
            bases=('projects.mediaitem',),
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('mediaitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.MediaItem')),
                ('file', models.ImageField(height_field='height', upload_to=projects.models.MediaItem.upload_to, width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('projects.mediaitem',),
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('mediaitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.MediaItem')),
                ('file', models.FileField(upload_to=projects.models.MediaItem.upload_to, validators=[projects.models.FileValidatorFunction(allowed_extensions=[], allowed_mimetypes=['video/mpg', 'video/mov', 'application/csv'], max_file_size=None)])),
            ],
            options={
                'abstract': False,
            },
            bases=('projects.mediaitem',),
        ),
    ]
