# Generated by Django 3.0.5 on 2020-05-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True)),
                ('status', models.IntegerField(db_index=True, help_text='The status changed to this value')),
                ('timestamp', models.DateTimeField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Status change histories',
                'ordering': ('-timestamp',),
                'unique_together': {('content_type', 'object_id', 'status', 'timestamp')},
            },
        ),
    ]
